#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
OUT_DIR="${BASE_DIR}/out"
SED_SCRIPT="${BASE_DIR}/mtype.sed"
PAN="${1:-$BASE_DIR/pan}"


(cd "$BASE_DIR"
	git clean -fdx "$OUT_DIR"
	mkdir -p "$OUT_DIR"
	"$PAN" -D > "${OUT_DIR}/diagram"

	sed -E -f "$SED_SCRIPT" -i '.raw' "${OUT_DIR}/diagram"

	(cd "$OUT_DIR"
		dot -Kdot -Tsvg -O ./diagram
	)
)
